name: pysap
channels:
  - conda-forge
  - astra-toolbox
dependencies:
  - python=3.9
  - astra-toolbox>=2.0.0
  - jupyter>=1.0.0
  - matplotlib>=3.3.4
  - pynfft>=1.3.2
  - pynufft>=2021.2.1
  - pip
  - pip:
    - astropy>=4.1
    - joblib>=1.0.1
    - modopt>=1.5.1
    - nibabel>=3.2.1
    - numpy>=1.19.5
    - progressbar2>=3.53.1
    - pyqtgraph>=0.11.1
    - PyWavelets>=1.1.1
    - scikit-image>=0.17.2
    - scikit-learn>=0.24.1
    - scipy>=1.5.4
    - sf_tools>=2.0.4
    - termcolor>=1.1.0
    - git+https://github.com/AGrigis/pysphinxdoc.git
